######################################################################
# PixInsight Makefile Generator Script v1.129
# Copyright (C) 2009-2023 Pleiades Astrophoto
######################################################################
# Generated on .... 2023-08-28T15:27:17.607Z
# Project id ...... PCL
# Project type .... StaticLibrary
# Platform ........ FreeBSD/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

