set PCLDIR=%USERPROFILE%\work\PCL
set PCLBINDIR64=%PCLDIR%\bin
set PCLBINDIR=%PCLBINDIR64%
set PCLLIBDIR64=%PCLDIR%\lib\windows\x64
set PCLLIBDIR=%PCLLIBDIR64%
set PCLINCDIR=%PCLDIR%\include
set PCLSRCDIR=%PCLDIR%\src