PCLDIR=%USERPROFILE%\Documents\PixInsight\PCL
PCLBINDIR64=%PCLDIR%\bin
PCLBINDIR=%PCLBINDIR64%
PCLLIBDIR64=%PCLDIR%\lib\windows\x64
PCLLIBDIR=%PCLLIBDIR64%
PCLINCDIR=%PCLDIR%\include
PCLSRCDIR=%PCLDIR%\src