$env:PCLDIR = "$env:USERPROFILE\Documents\PixInsight\PCL"
$env:PCLBINDIR64 = "$env:PCLDIR\bin"
$env:PCLBINDIR = "$env:PCLBINDIR64"
$env:PCLLIBDIR64 = "$env:PCLDIR\lib\windows\x64"
$env:PCLLIBDIR = "$env:PCLLIBDIR64"
$env:PCLINCDIR = "$env:PCLDIR\include"
$env:PCLSRCDIR = "$env:PCLDIR\src"