######################################################################
# PixInsight Makefile Generator Script v1.121
# Copyright (C) 2009-2020 Pleiades Astrophoto
######################################################################
# Generated on .... 2020-12-15T20:12:51.217Z
# Project id ...... ColorCalibration
# Project type .... Module
# Platform ........ FreeBSD/g++ (compatibility)
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

