######################################################################
# PixInsight Makefile Generator Script v1.131
# Copyright (C) 2009-2023 Pleiades Astrophoto
######################################################################
# Generated on .... 2023-11-25T20:21:19.307Z
# Project id ...... JPEG2000
# Project type .... Module
# Platform ........ Linux/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

