######################################################################
# PixInsight Makefile Generator Script v1.126
# Copyright (C) 2009-2022 Pleiades Astrophoto
######################################################################
# Generated on .... 2022-05-17T19:53:26.402Z
# Project id ...... Morphology
# Project type .... Module
# Platform ........ FreeBSD/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

