######################################################################
# PixInsight Makefile Generator Script v1.122
# Copyright (C) 2009-2021 Pleiades Astrophoto
######################################################################
# Generated on .... 2021-04-09T20:05:11.510Z
# Project id ...... PCL
# Project type .... StaticLibrary
# Platform ........ MacOSX/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

