######################################################################
# PixInsight Makefile Generator Script v1.121
# Copyright (C) 2009-2021 Pleiades Astrophoto
######################################################################
# Generated on .... 2021-01-20T20:18:06.466Z
# Project id ...... PixelMath
# Project type .... Module
# Platform ........ MacOSX/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

