######################################################################
# PixInsight Makefile Generator Script v1.119
# Copyright (C) 2009-2020 Pleiades Astrophoto
######################################################################
# Generated on .... 2020-10-12T19:29:55.032Z
# Project id ...... Image
# Project type .... Module
# Platform ........ Linux/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

