######################################################################
# PixInsight Makefile Generator Script v1.138
# Copyright (C) 2009-2024 Pleiades Astrophoto
######################################################################
# Generated on .... 2024-05-07T16:57:56.524Z
# Project id ...... BMP
# Project type .... Module
# Platform ........ MacOSX/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

