######################################################################
# PixInsight Makefile Generator Script v1.117
# Copyright (C) 2009-2020 Pleiades Astrophoto
######################################################################
# Generated on .... 2020-02-04T17:14:32.865Z
# Project id ...... ImageIntegration
# Project type .... Module
# Platform ........ Linux/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

