######################################################################
# PixInsight Makefile Generator Script v1.112
# Copyright (C) 2009-2019 Pleiades Astrophoto
######################################################################
# Generated on .... 2019-09-30T11:28:01.018Z
# Project id ...... installer
# Project type .... X11Installer
# Platform ........ Linux/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

