######################################################################
# PixInsight Makefile Generator Script v1.132
# Copyright (C) 2009-2024 Pleiades Astrophoto
######################################################################
# Generated on .... 2024-01-14T19:42:16.447Z
# Project id ...... Sandbox
# Project type .... Module
# Platform ........ Linux/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

