######################################################################
# PixInsight Makefile Generator Script v1.129
# Copyright (C) 2009-2023 Pleiades Astrophoto
######################################################################
# Generated on .... 2023-06-22T07:13:53.076Z
# Project id ...... Convolution
# Project type .... Module
# Platform ........ FreeBSD/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

