######################################################################
# PixInsight Makefile Generator Script v1.110
# Copyright (C) 2009-2019 Pleiades Astrophoto
######################################################################
# Generated on .... 2019-04-30T16:35:46.338Z
# Project id ...... Debayer
# Project type .... Module
# Platform ........ Linux/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

