######################################################################
# PixInsight Makefile Generator Script v1.122
# Copyright (C) 2009-2021 Pleiades Astrophoto
######################################################################
# Generated on .... 2021-04-12T15:30:11.152Z
# Project id ...... INDIClient
# Project type .... Module
# Platform ........ Linux/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

