######################################################################
# PixInsight Makefile Generator Script v1.129
# Copyright (C) 2009-2023 Pleiades Astrophoto
######################################################################
# Generated on .... 2023-05-17T18:34:42.087Z
# Project id ...... XISF
# Project type .... Module
# Platform ........ Linux/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

