######################################################################
# PixInsight Makefile Generator Script v1.117
# Copyright (C) 2009-2019 Pleiades Astrophoto
######################################################################
# Generated on .... 2019-12-13T16:39:22.770Z
# Project id ...... RAW-compat
# Project type .... Module
# Platform ........ Linux/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

