######################################################################
# PixInsight Makefile Generator Script v1.133
# Copyright (C) 2009-2024 Pleiades Astrophoto
######################################################################
# Generated on .... 2024-01-22T10:20:54.011Z
# Project id ...... RAW-compat
# Project type .... Module
# Platform ........ Linux/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

