######################################################################
# PixInsight Makefile Generator Script v1.126
# Copyright (C) 2009-2022 Pleiades Astrophoto
######################################################################
# Generated on .... 2022-04-22T19:32:50.070Z
# Project id ...... NoOperation
# Project type .... Module
# Platform ........ FreeBSD/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

