######################################################################
# PixInsight Makefile Generator Script v1.125
# Copyright (C) 2009-2022 Pleiades Astrophoto
######################################################################
# Generated on .... 2022-01-24T21:06:30.551Z
# Project id ...... PCL
# Project type .... StaticLibrary
# Platform ........ Linux/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

