######################################################################
# PixInsight Makefile Generator Script v1.142
# Copyright (C) 2009-2024 Pleiades Astrophoto
######################################################################
# Generated on .... 2024-12-11T21:18:00.958Z
# Project id ...... FITS
# Project type .... Module
# Platform ........ FreeBSD/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

