######################################################################
# PixInsight Makefile Generator Script v1.123
# Copyright (C) 2009-2021 Pleiades Astrophoto
######################################################################
# Generated on .... 2021-10-04T16:23:55.886Z
# Project id ...... Global
# Project type .... Module
# Platform ........ FreeBSD/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

