######################################################################
# PixInsight Makefile Generator Script v1.118
# Copyright (C) 2009-2020 Pleiades Astrophoto
######################################################################
# Generated on .... 2020-07-31T19:36:28.347Z
# Project id ...... CloneStamp
# Project type .... Module
# Platform ........ FreeBSD/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

