######################################################################
# PixInsight Makefile Generator Script v1.114
# Copyright (C) 2009-2019 Pleiades Astrophoto
######################################################################
# Generated on .... 2019-11-15T11:04:20.308Z
# Project id ...... ImageIntegration
# Project type .... Module
# Platform ........ MacOSX/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

