######################################################################
# PixInsight Makefile Generator Script v1.126
# Copyright (C) 2009-2022 Pleiades Astrophoto
######################################################################
# Generated on .... 2022-05-18T08:56:55.926Z
# Project id ...... ImageCalibration
# Project type .... Module
# Platform ........ FreeBSD/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

