######################################################################
# PixInsight Makefile Generator Script v1.129
# Copyright (C) 2009-2023 Pleiades Astrophoto
######################################################################
# Generated on .... 2023-08-10T14:43:49.905Z
# Project id ...... CometAlignment
# Project type .... Module
# Platform ........ MacOSX/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

