######################################################################
# PixInsight Makefile Generator Script v1.127
# Copyright (C) 2009-2022 Pleiades Astrophoto
######################################################################
# Generated on .... 2022-12-07T20:24:23.173Z
# Project id ...... astjpl2pcl
# Project type .... Executable
# Platform ........ Linux/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

